specVersion: 0.2.0
name: moonbeam-distribution-subql
version: 0.1.0
description: subquery diction for moonbase-alpha and ...
repository: https://github.com/parallel-finance/moonbeam-distribution-subql
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 208196
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
