specVersion: 1.0.0
name: moonbeam-distribution-subql
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: subquery diction for moonbase-alpha and ...
repository: https://github.com/rjman-ljm/parallel-moonbeam-distribution-subql
schema:
  file: ./schema.graphql
network:
  chainId: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d"
  endpoint: "wss://moonbeam.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/moonbeam-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    # startBlock: 208196
    startBlock: 1081261
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
